# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gssbg5kPtJvMOy9dCwlwDZ8MHGTeEzV5
"""

# @title
pip install gradio regex pandas

import gradio as gr
import regex as re
import pandas as pd

# Hindi Matras
MATRAS = set([
    'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'े', 'ै', 'ो', 'ौ', 'ॅ', 'ॉ', 'ॆ', 'ॊ'
])

# Hindi signs
SIGNS = set(['ं', 'ँ', 'ः', '़', '्'])

def analyze_hindi_text(text):
    if not text or not text.strip():
        return (
            "Please enter Hindi text.",
            0,
            0,
            0,
            0,
            0,
            pd.DataFrame(columns=["Word", "Raw Length", "Visible Units", "Matras"])
        )

    words = text.split()

    # Grapheme clusters (visible units)
    graphemes = re.findall(r'\X', text)
    visible_units = [g for g in graphemes if re.search(r'[\p{Devanagari}]', g)]

    matra_count = sum(1 for ch in text if ch in MATRAS)
    sign_count = sum(1 for ch in text if ch in SIGNS)

    word_details = []
    for word in words:
        word_graphemes = re.findall(r'\X', word)
        word_visible_units = [g for g in word_graphemes if re.search(r'[\p{Devanagari}]', g)]
        word_matra_count = sum(1 for ch in word if ch in MATRAS)

        word_details.append({
            "Word": word,
            "Raw Length": len(word),
            "Visible Units": len(word_visible_units),
            "Matras": word_matra_count
        })

    df = pd.DataFrame(word_details)

    summary = f"""
### Analysis Summary
- **Input Text:** {text}
- **Raw Character Length:** {len(text)}
- **Word Count:** {len(words)}
- **Visible Hindi Units:** {len(visible_units)}
- **Matra Count:** {matra_count}
- **Sign Count:** {sign_count}
"""

    return (
        summary,
        len(text),
        len(words),
        len(visible_units),
        matra_count,
        sign_count,
        df
    )

# Gradio UI
with gr.Blocks(theme=gr.themes.Soft(), title="Hindi Text Analyzer") as demo:
    gr.Markdown("# Hindi Text Analyzer")
    gr.Markdown("Analyze Hindi text for word count, visible letter units, matras, and more.")

    with gr.Row():
        text_input = gr.Textbox(
            label="Enter Hindi Text",
            placeholder="Type Hindi sentence here...",
            lines=4
        )

    analyze_btn = gr.Button("Analyze Text")

    with gr.Row():
        raw_len = gr.Number(label="Raw Character Length")
        word_count = gr.Number(label="Word Count")
        visible_count = gr.Number(label="Visible Hindi Units")

    with gr.Row():
        matra_count = gr.Number(label="Matra Count")
        sign_count = gr.Number(label="Sign Count")

    summary_output = gr.Markdown(label="Summary")
    table_output = gr.Dataframe(label="Word-Level Analysis", interactive=False)

    analyze_btn.click(
        fn=analyze_hindi_text,
        inputs=text_input,
        outputs=[
            summary_output,
            raw_len,
            word_count,
            visible_count,
            matra_count,
            sign_count,
            table_output
        ]
    )

demo.launch()

